// One-line contract notes for demos whose source does not already explain a non-obvious behavior.
// Package re-exports share a title entry because their runtime contract is identical.
export const demoNotes = {
  createOptimistic:
    "The accessor exposes the optimistic value while the action is pending and its settled value afterward.",
  createReaction: "The tracked callback is armed explicitly and runs once for each subsequent invalidation.",
  createRenderEffect: "The render effect writes to the DOM immediately and again whenever its source changes.",
  createTrackedEffect: "Each rerun invokes the cleanup returned by the previous tracked execution.",
  enableHydration: "Hydration mode enables the runtime context consumed by later hydration-aware rendering.",
  flush: "flush commits the queued signal update before the click handler continues.",
  lazy: "The module loader starts only after the lazy component is mounted, then resolves the pending boundary.",
  mapArray: "Mapped row nodes retain identity while the source array is reordered.",
  repeat: "The callback receives each index in the requested numeric range and reruns when the count changes.",
  isWrappable: "Only values that can participate in a reactive store proxy report true.",
  reconcile: "Rows with matching keys preserve proxy identity while their fields and membership are reconciled.",
  snapshot: "A snapshot remains plain and unchanged until another snapshot is explicitly taken.",
  action: "The action exposes its optimistic write before the yielded work settles.",
  getOwner: "Owner lookup succeeds during render but not inside a later event callback.",
  createRoot: "The independent Owner keeps its own signal alive until its disposer is called.",
  getObserver: "Observer lookup is empty outside tracking and available while an effect reads its source.",
  isDisposed: "The same Owner changes from active to disposed after its root disposer runs.",
  enableExternalSource: "The adapter connects an external tracking protocol to a memo derived from a Solid signal.",
  isPending: "The accessor distinguishes a pending transition from its settled state.",
  resolve: "resolve flushes the projected write so the committed value is observable immediately.",
  Dynamic: "Changing the component value replaces the rendered element type while preserving its children.",
  Errored: "The boundary reads the thrown error through its accessor and reset remounts protected content.",
  For: "Keyed list rows preserve identity while additions and removals update the collection.",
  Hydration: "Hydration re-enables bindings inside a surrounding non-hydrated server subtree.",
  HydrationScript: "The server renderer emits the bootstrap script required by client hydration.",
  Loading: "The boundary moves through idle, pending fallback, and resolved content states.",
  Match: "A Match renders only when selected by its enclosing Switch.",
  NoHydration: "The marked server subtree is emitted without client hydration bindings.",
  Portal: "The child is created from this source position but mounted in the explicit target container.",
  Repeat: "Repeat renders the requested count of numeric rows from the configured starting index.",
  Reveal: "Sequential order withholds the second resolved section until the first section is ready.",
  Show: "The keyed branch receives the matched value and is recreated when that value changes.",
  Switch: "Switch renders the first matching branch and falls back when none match.",
  hydrate: "Hydration attaches reactivity to the existing server node instead of replacing it.",
  render: "render mounts the callback result and returns ownership of its cleanup lifecycle.",
  renderToStream: "The stream exposes rendered HTML through its asynchronous completion contract.",
  renderToString: "The renderer serializes JSX into an HTML string without a browser DOM.",
  getRequestEvent: "Repeated reads return the same request event stored in the active SSR context.",
  httpHeader: "Header writes mutate the active request response before it is committed.",
  httpStatus: "Status writes mutate the active request response before it is committed.",
  isHref: "The predicate distinguishes navigation targets accepted by the router helpers.",
  isResponseEnvelope: "Only the value created by respond satisfies the response-envelope contract.",
  redirect: "The helper creates a redirect response with the requested status and Location header.",
  reload: "The helper preserves custom response options while marking the result for reload handling.",
  respond: "The envelope carries its value together with response status and headers.",
  clientOnly: "The component module is requested and rendered only in the browser runtime.",
  dynamic: "The low-level dynamic helper resolves a reactive intrinsic element type.",
  dynamicProperty: "The property accessor follows the current key and returns the matching object value.",
  effect: "The runtime effect writes each observed source value into the same DOM node.",
  getDelegatedRoot: "Lookup walks from the child to the root registered for delegated events.",
  registerDelegatedRoot: "Registration makes the mount discoverable as a delegated event root.",
  registerDelegatedContainer: "The nested container delegates through the explicitly registered owner root.",
  unregisterDelegatedContainer: "Removing the same container-owner pair stops nested delegation through that root.",
  unregisterDelegatedRoot: "Unregistration removes the mount from delegated-root lookup.",
};
